# Generated by Django 5.0.6 on 2024-06-13 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('general_instructions', models.TextField(blank=True, null=True, verbose_name='General instructions')),
                ('terminology', models.TextField(blank=True, null=True, verbose_name='Terminology')),
                ('template_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Template name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('template_content', models.BinaryField(blank=True, null=True, verbose_name='Template content')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_settings',
                'ordering': ['id'],
            },
        ),
    ]
