# Generated by Django 5.0.6 on 2024-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usersettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='project_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Project instructions'),
        ),
    ]
