version: "3.8"


volumes:
  data-redis:
  data-postgres:


services:

  server:
    build:
      context: ../../
      dockerfile: server.Dockerfile
    restart: always
    volumes:
      - ../../server_static:/web_app/server_static
      - ../../media:/web_app/media
      - ../../microservices_tasks:/web_app/microservices_tasks
      - ../../ppt_projects:/web_app/ppt_projects
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  celery-mail-worker:
    build:
      context: ../../
      dockerfile: celery.Dockerfile
      # command: celery --app server worker -Q openai,mail_notification,ppt_task_creator -c 5 --loglevel=info
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6355:6379'
    logging:
      options:
        max-file: "5"
        max-size: "5m"

  postgres:
    image: postgres
    restart: always
    ports:
      - '5481:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    logging:
      options:
        max-file: "5"
        max-size: "5m"