# Generated by Django 5.0.6 on 2024-06-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePPTTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('ppt_template_hash', models.TextField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('footer', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ppt_template', models.BinaryField(blank=True, null=True)),
                ('created_ppt_content', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'create_ppt_tasks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreateScreenshotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uid', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('content_hash', models.TextField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending')),
                ('status_message', models.TextField(blank=True, null=True)),
                ('content', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'create_screenshot_tasks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreatePPTTaskSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('slide_option', models.IntegerField()),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screenshot', models.BinaryField(blank=True, null=True)),
                ('ppt_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppt_task', to='microservices_tasks.createppttask')),
            ],
            options={
                'db_table': 'create_ppt_tasks_slides',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreateScreenshotTaskScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.BinaryField()),
                ('screenshot_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='microservices_tasks.createscreenshottask')),
            ],
            options={
                'db_table': 'create_screenshot_tasks_screenshots',
                'ordering': ['id'],
            },
        ),
    ]
