# Generated by Django 5.0.6 on 2024-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createppttaskslide',
            name='spreadsheet_screenshot',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
