# Generated by Django 5.0.6 on 2024-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0003_alter_createppttask_id_alter_createppttaskslide_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createppttask',
            name='client_uid',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='createscreenshottask',
            name='client_uid',
            field=models.TextField(db_index=True),
        ),
    ]
