# Generated by Django 5.0.6 on 2024-06-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0004_alter_createppttask_client_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createppttaskslide',
            name='ppt_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppt_task_slides', to='microservices_tasks.createppttask'),
        ),
    ]
