# Generated by Django 5.0.6 on 2024-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0005_alter_createppttaskslide_ppt_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createppttask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='createppttask',
            name='ppt_template_hash',
        ),
        migrations.AlterField(
            model_name='createppttask',
            name='client_uid',
            field=models.TextField(default='backend'),
        ),
        migrations.AlterField(
            model_name='createscreenshottask',
            name='client_uid',
            field=models.TextField(default='backend'),
        ),
    ]
