# Generated by Django 5.0.6 on 2024-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0006_remove_createppttask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createscreenshottask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='pending'),
        ),
    ]
