# Generated by Django 5.0.6 on 2024-06-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0007_alter_createscreenshottask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createscreenshottask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING'),
        ),
    ]
