# Generated by Django 5.0.6 on 2024-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0009_alter_createscreenshottask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='createscreenshottaskscreenshot',
            name='screenshot_first_slide',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
