# Generated by Django 5.0.6 on 2024-06-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0010_createscreenshottaskscreenshot_screenshot_first_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createscreenshottaskscreenshot',
            name='screenshot_first_slide',
        ),
        migrations.AddField(
            model_name='createppttask',
            name='screenshot_first_slide',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
