# Generated by Django 5.0.6 on 2024-06-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0011_remove_createscreenshottaskscreenshot_screenshot_first_slide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createppttask',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
