# Generated by Django 5.0.6 on 2024-07-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices_tasks', '0012_alter_createppttask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicatePPTSlidesTask',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('client_uid', models.TextField()),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('ppt_in', models.BinaryField()),
                ('ppt_out', models.BinaryField(blank=True, null=True)),
                ('target_count', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'duplicate_ppt_slides_tasks',
                'ordering': ['id'],
            },
        ),
    ]
