# Generated by Django 5.0.6 on 2024-06-19 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputWorkbook',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('content', models.BinaryField(verbose_name='Content')),
            ],
            options={
                'db_table': 'input_workbooks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InputSpreadsheet',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('screenshot', models.BinaryField(blank=True, null=True, verbose_name='Screenshot')),
                ('content', models.BinaryField(blank=True, null=True, verbose_name='Content')),
                ('input_workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_spreadsheets', to='ppt_projects.inputworkbook')),
            ],
            options={
                'db_table': 'input_spreadsheets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer')),
                ('template_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Template name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('template_content', models.BinaryField(blank=True, null=True, verbose_name='Template content')),
                ('ppt_content', models.BinaryField(blank=True, null=True, verbose_name='PPT content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inputworkbook',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_workbooks', to='ppt_projects.project'),
        ),
        migrations.CreateModel(
            name='SlideInstructions',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('position', models.IntegerField(verbose_name='Position')),
                ('name', models.CharField(default='Slide <django.db.models.fields.IntegerField>', max_length=100, verbose_name='Name')),
                ('perform_analysis', models.BooleanField(default=False, verbose_name='Perform analysis?')),
                ('display_on_slide', models.BooleanField(default=False, verbose_name='Display on slide?')),
                ('slide_option', models.IntegerField(verbose_name='Slide Option')),
                ('specific_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specific title')),
                ('specific_instructions', models.TextField(blank=True, null=True, verbose_name='Specific instructions')),
                ('generated_text', models.TextField(blank=True, null=True, verbose_name='Generated text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='slides/screenshot', verbose_name='Screenshot')),
                ('input_spreadsheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppt_projects.inputspreadsheet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_instructions', to='ppt_projects.project')),
            ],
            options={
                'db_table': 'slide_instructions',
                'ordering': ['id'],
            },
        ),
    ]
