# Generated by Django 5.0.6 on 2024-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='PPT Project', max_length=255, verbose_name='Title'),
        ),
    ]
