# Generated by Django 5.0.6 on 2024-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_projects', '0002_remove_project_name_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_generating',
            field=models.BooleanField(default=False, verbose_name='Is generating?'),
        ),
    ]
