# Generated by Django 5.0.6 on 2024-06-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_projects', '0004_project_screenshot_first_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot_first_slide',
            field=models.FileField(blank=True, null=True, upload_to='slides/screenshot', verbose_name='Screenshot'),
        ),
    ]
